apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

openapi:
  path: https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_all_k8s_kustomize_schema.json

patchesStrategicMerge:
- |-
  apiVersion: argoproj.io/v1alpha1
  kind: Rollout
  metadata:
    name: ro-simpleapp
    labels:
      app: ro-simpleapp
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ro-simpleapp
    revisionHistoryLimit: 2
    template:
      metadata:
        labels:
          app: ro-simpleapp
      spec:
        containers:
          - name: httpd
            image: tvminh/simpleapp:production

