apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp-canary
  labels:
    app: simpleapp
    version: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleapp
      version: canary
  template:
    metadata:
      labels:
        app: simpleapp
        version: canary
    spec:
      containers:
        - name: simpleapp-canary
          imagePullPolicy: Always
          image: tvminh/simpleapp:canary
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapp-canary
spec:
  selector:
    app: simpleapp-canary
  ports:
    - port: 80
      targetPort: http
