apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp
  labels:
    app: simpleapp
    version: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleapp
      version: prod
  template:
    metadata:
      labels:
        app: simpleapp
        version: prod
      # annotations:
      #   vault.hashicorp.com/agent-inject: 'true'
      #   vault.hashicorp.com/role: 'devweb-app'
      #   vault.hashicorp.com/agent-inject-secret-database-config.txt: 'internal/data/database/config'
      #   vault.hashicorp.com/agent-init-first: 'true'
      #   vault.hashicorp.com/agent-inject-status: 'update'
      #   vault.hashicorp.com/agent-inject-template-database-config.txt: |
      #     {{- with secret "internal/data/database/config" -}}
      #     username: {{ .Data.data.username }}
      #     password: {{ .Data.data.password }}
      #     {{- end -}}
    spec:
      serviceAccountName: internal-app
      containers:
        - name: simpleapp
          imagePullPolicy: Always
          image: tvminh/simpleapp:production 
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapp
spec:
  selector:
    app: simpleapp
  ports:
    - port: 80
      targetPort: http
